function beehive_flow(time,temp_beehive, temp_environment, number_bees, ...
    heat_production, insolation, efficiency_of_absorption, projected_area, ...
    thickness_bubble_wrap, thickness_blue_foam, thickness_wall, ...
    thermal_conductivity_bubble_wrap, thermal_conductivity_blue_foam, ...
    thermal_conductivity_wall, area_of_contact, heat_transfer_coefficient_of_air)
    temp_delta = temp_beehive - temp_environment;
    
    %%four flow functions
    heat_production_total = heat_production_single
end